services:
  - type: web
    name: fullstack-capstone
    env: python
    plan: free
    buildCommand: |
      pip install -r ./server/requirements.txt
      cd server/frontend && npm install && npm run build
      cd ..
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      # Add your secrets below, e.g. DATABASE_URL, SECRET_KEY, etc.
      # - key: SECRET_KEY
      #   sync: false
